import type { CodingTestCase } from "@/lib/mock-tests/types";

export type PracticeLanguage = "javascript" | "python";
export type PracticeTopic = "strings" | "arrays";

export interface DsaPracticeQuestion {
  id: string;
  topic: PracticeTopic;
  title: string;
  difficulty: "easy" | "medium" | "hard";
  pattern: string;
  statement: string;
  constraints: string[];
  functionName: Record<PracticeLanguage, string>;
  starter: Record<PracticeLanguage, string>;
  sampleCases: CodingTestCase[];
  testCases: CodingTestCase[];
}

const strings: DsaPracticeQuestion[] = [
  {
    id: "STR-01",
    topic: "strings",
    title: "Clean palindrome",
    difficulty: "easy",
    pattern: "Two pointers",
    statement: "Return true when the text reads the same forwards and backwards after ignoring spaces, punctuation and letter case.",
    constraints: ["The input is a string", "Only letters and digits participate in the comparison"],
    functionName: { javascript: "isCleanPalindrome", python: "is_clean_palindrome" },
    starter: {
      javascript: "function isCleanPalindrome(text) {\n  // Return true or false\n}\n",
      python: "def is_clean_palindrome(text):\n    # Return True or False\n    pass\n",
    },
    sampleCases: [
      { input: ["Never odd or even"], expected: true },
      { input: ["SQL battle"], expected: false },
    ],
    testCases: [
      { input: ["Never odd or even"], expected: true },
      { input: ["SQL battle"], expected: false },
      { input: ["A man, a plan, a canal: Panama!"], expected: true, hidden: true },
      { input: [""], expected: true, hidden: true },
      { input: ["0P"], expected: false, hidden: true },
    ],
  },
  {
    id: "STR-02",
    topic: "strings",
    title: "First unique character",
    difficulty: "easy",
    pattern: "Frequency map",
    statement: "Return the zero-based index of the first character that appears exactly once. Return -1 when every character repeats.",
    constraints: ["Comparison is case-sensitive", "The string may be empty"],
    functionName: { javascript: "firstUniqueIndex", python: "first_unique_index" },
    starter: {
      javascript: "function firstUniqueIndex(text) {\n  // Return an index or -1\n}\n",
      python: "def first_unique_index(text):\n    # Return an index or -1\n    pass\n",
    },
    sampleCases: [
      { input: ["placement"], expected: 0 },
      { input: ["aabbcc"], expected: -1 },
    ],
    testCases: [
      { input: ["placement"], expected: 0 },
      { input: ["aabbcc"], expected: -1 },
      { input: ["swiss"], expected: 1, hidden: true },
      { input: ["aabbccd"], expected: 6, hidden: true },
      { input: [""], expected: -1, hidden: true },
    ],
  },
  {
    id: "STR-03",
    topic: "strings",
    title: "Anagram check",
    difficulty: "easy",
    pattern: "Counting",
    statement: "Return true when two strings contain the same letters with the same frequencies, ignoring spaces and letter case.",
    constraints: ["Inputs contain letters and spaces", "Do not assume the words have equal length before cleaning"],
    functionName: { javascript: "areAnagrams", python: "are_anagrams" },
    starter: {
      javascript: "function areAnagrams(first, second) {\n  // Return true or false\n}\n",
      python: "def are_anagrams(first, second):\n    # Return True or False\n    pass\n",
    },
    sampleCases: [
      { input: ["Dormitory", "Dirty room"], expected: true },
      { input: ["listen", "silentx"], expected: false },
    ],
    testCases: [
      { input: ["Dormitory", "Dirty room"], expected: true },
      { input: ["listen", "silentx"], expected: false },
      { input: ["Conversation", "Voices rant on"], expected: true, hidden: true },
      { input: ["aab", "abb"], expected: false, hidden: true },
    ],
  },
  {
    id: "STR-04",
    topic: "strings",
    title: "Longest distinct window",
    difficulty: "medium",
    pattern: "Sliding window",
    statement: "Return the length of the longest contiguous substring containing no repeated characters.",
    constraints: ["The input may be empty", "Aim for linear time"],
    functionName: { javascript: "longestDistinctLength", python: "longest_distinct_length" },
    starter: {
      javascript: "function longestDistinctLength(text) {\n  // Return the maximum window length\n}\n",
      python: "def longest_distinct_length(text):\n    # Return the maximum window length\n    pass\n",
    },
    sampleCases: [
      { input: ["abcabcbb"], expected: 3 },
      { input: ["bbbbb"], expected: 1 },
    ],
    testCases: [
      { input: ["abcabcbb"], expected: 3 },
      { input: ["bbbbb"], expected: 1 },
      { input: ["pwwkew"], expected: 3, hidden: true },
      { input: [""], expected: 0, hidden: true },
      { input: ["dvdf"], expected: 3, hidden: true },
    ],
  },
  {
    id: "STR-05",
    topic: "strings",
    title: "Balanced brackets",
    difficulty: "medium",
    pattern: "Stack",
    statement: "Return true when every opening bracket in the string is closed by the correct bracket in the correct order.",
    constraints: ["The input contains only (), [] and {}", "An empty string is balanced"],
    functionName: { javascript: "hasBalancedBrackets", python: "has_balanced_brackets" },
    starter: {
      javascript: "function hasBalancedBrackets(text) {\n  // Return true or false\n}\n",
      python: "def has_balanced_brackets(text):\n    # Return True or False\n    pass\n",
    },
    sampleCases: [
      { input: ["{[()]}"], expected: true },
      { input: ["([)]"], expected: false },
    ],
    testCases: [
      { input: ["{[()]}"], expected: true },
      { input: ["([)]"], expected: false },
      { input: [""], expected: true, hidden: true },
      { input: ["((()))[]{}"], expected: true, hidden: true },
      { input: ["{{}"], expected: false, hidden: true },
    ],
  },
  {
    id: "STR-06",
    topic: "strings",
    title: "Run-length compression",
    difficulty: "medium",
    pattern: "String traversal",
    statement: "Compress consecutive equal characters as the character followed by its count. Keep single characters without a count.",
    constraints: ["Characters are case-sensitive", "Return an empty string for empty input"],
    functionName: { javascript: "compressRuns", python: "compress_runs" },
    starter: {
      javascript: "function compressRuns(text) {\n  // Example: aaabbc -> a3b2c\n}\n",
      python: "def compress_runs(text):\n    # Example: aaabbc -> a3b2c\n    pass\n",
    },
    sampleCases: [
      { input: ["aaabbc"], expected: "a3b2c" },
      { input: ["abcd"], expected: "abcd" },
    ],
    testCases: [
      { input: ["aaabbc"], expected: "a3b2c" },
      { input: ["abcd"], expected: "abcd" },
      { input: ["xxxxxxxxxx"], expected: "x10", hidden: true },
      { input: ["aAAaa"], expected: "aA2a2", hidden: true },
      { input: [""], expected: "", hidden: true },
    ],
  },
  {
    id: "STR-07", topic: "strings", title: "Reverse word order", difficulty: "easy", pattern: "Tokenisation",
    statement: "Return the words in reverse order, removing leading, trailing and repeated spaces.",
    constraints: ["Words are separated by spaces", "The result must contain single spaces only"],
    functionName: { javascript: "reverseWords", python: "reverse_words" },
    starter: { javascript: "function reverseWords(text) {\n  // Return the words in reverse order\n}\n", python: "def reverse_words(text):\n    # Return the words in reverse order\n    pass\n" },
    sampleCases: [{ input: ["learn SQL daily"], expected: "daily SQL learn" }, { input: ["  campus   ready  "], expected: "ready campus" }],
    testCases: [{ input: ["learn SQL daily"], expected: "daily SQL learn" }, { input: ["  campus   ready  "], expected: "ready campus" }, { input: ["single"], expected: "single", hidden: true }, { input: ["   "], expected: "", hidden: true }],
  },
  {
    id: "STR-08", topic: "strings", title: "Count vowels", difficulty: "easy", pattern: "Linear scan",
    statement: "Return the number of vowels in the text. Treat upper-case and lower-case vowels equally.",
    constraints: ["Count a, e, i, o and u", "Other characters are ignored"],
    functionName: { javascript: "countVowels", python: "count_vowels" },
    starter: { javascript: "function countVowels(text) {\n  // Return the vowel count\n}\n", python: "def count_vowels(text):\n    # Return the vowel count\n    pass\n" },
    sampleCases: [{ input: ["Accenture"], expected: 4 }, { input: ["rhythm"], expected: 0 }],
    testCases: [{ input: ["Accenture"], expected: 4 }, { input: ["rhythm"], expected: 0 }, { input: ["AEIOU"], expected: 5, hidden: true }, { input: [""], expected: 0, hidden: true }],
  },
  {
    id: "STR-09", topic: "strings", title: "Remove duplicate characters", difficulty: "easy", pattern: "Set",
    statement: "Remove repeated characters while keeping only the first occurrence of each character.",
    constraints: ["Comparison is case-sensitive", "Preserve the original order"],
    functionName: { javascript: "removeDuplicateCharacters", python: "remove_duplicate_characters" },
    starter: { javascript: "function removeDuplicateCharacters(text) {\n  // Keep each character once\n}\n", python: "def remove_duplicate_characters(text):\n    # Keep each character once\n    pass\n" },
    sampleCases: [{ input: ["programming"], expected: "progamin" }, { input: ["aaaa"], expected: "a" }],
    testCases: [{ input: ["programming"], expected: "progamin" }, { input: ["aaaa"], expected: "a" }, { input: ["AaA"], expected: "Aa", hidden: true }, { input: [""], expected: "", hidden: true }],
  },
  {
    id: "STR-10", topic: "strings", title: "Longest common prefix", difficulty: "easy", pattern: "Prefix scan",
    statement: "Return the longest starting sequence shared by every string in the array.",
    constraints: ["Return an empty string when no common prefix exists", "The array contains at least one string"],
    functionName: { javascript: "longestCommonPrefix", python: "longest_common_prefix" },
    starter: { javascript: "function longestCommonPrefix(words) {\n  // Return the shared prefix\n}\n", python: "def longest_common_prefix(words):\n    # Return the shared prefix\n    pass\n" },
    sampleCases: [{ input: [["flower", "flow", "flight"]], expected: "fl" }, { input: [["dog", "race", "car"]], expected: "" }],
    testCases: [{ input: [["flower", "flow", "flight"]], expected: "fl" }, { input: [["dog", "race", "car"]], expected: "" }, { input: [["interspecies", "interstellar", "interstate"]], expected: "inters", hidden: true }, { input: [["solo"]], expected: "solo", hidden: true }],
  },
  {
    id: "STR-11", topic: "strings", title: "String rotation check", difficulty: "easy", pattern: "Concatenation",
    statement: "Return true when the second string can be formed by rotating the first string.",
    constraints: ["Both inputs are case-sensitive", "Rotations must have equal length"],
    functionName: { javascript: "isRotation", python: "is_rotation" },
    starter: { javascript: "function isRotation(first, second) {\n  // Return true or false\n}\n", python: "def is_rotation(first, second):\n    # Return True or False\n    pass\n" },
    sampleCases: [{ input: ["waterbottle", "erbottlewat"], expected: true }, { input: ["coding", "ingcodx"], expected: false }],
    testCases: [{ input: ["waterbottle", "erbottlewat"], expected: true }, { input: ["coding", "ingcodx"], expected: false }, { input: ["aaaa", "aaaa"], expected: true, hidden: true }, { input: ["", ""], expected: true, hidden: true }, { input: ["abc", "ab"], expected: false, hidden: true }],
  },
  {
    id: "STR-12", topic: "strings", title: "Word count", difficulty: "easy", pattern: "Tokenisation",
    statement: "Return the number of words separated by one or more whitespace characters.",
    constraints: ["Leading and trailing whitespace does not create words", "The input may be empty"],
    functionName: { javascript: "countWords", python: "count_words" },
    starter: { javascript: "function countWords(text) {\n  // Return the number of words\n}\n", python: "def count_words(text):\n    # Return the number of words\n    pass\n" },
    sampleCases: [{ input: ["prepare for placements"], expected: 3 }, { input: ["  one   two  "], expected: 2 }],
    testCases: [{ input: ["prepare for placements"], expected: 3 }, { input: ["  one   two  "], expected: 2 }, { input: [""], expected: 0, hidden: true }, { input: ["line one\nline two"], expected: 4, hidden: true }],
  },
  {
    id: "STR-13", topic: "strings", title: "First repeated character", difficulty: "easy", pattern: "Set",
    statement: "Return the first character whose second occurrence is encountered while scanning left to right. Return an empty string if none repeats.",
    constraints: ["Comparison is case-sensitive", "Spaces count as characters"],
    functionName: { javascript: "firstRepeatedCharacter", python: "first_repeated_character" },
    starter: { javascript: "function firstRepeatedCharacter(text) {\n  // Return one character or an empty string\n}\n", python: "def first_repeated_character(text):\n    # Return one character or an empty string\n    pass\n" },
    sampleCases: [{ input: ["abca"], expected: "a" }, { input: ["abcdef"], expected: "" }],
    testCases: [{ input: ["abca"], expected: "a" }, { input: ["abcdef"], expected: "" }, { input: ["abccba"], expected: "c", hidden: true }, { input: ["AaA"], expected: "A", hidden: true }],
  },
  {
    id: "STR-14", topic: "strings", title: "Repeated substring pattern", difficulty: "medium", pattern: "Pattern matching",
    statement: "Return true when the entire string can be built by repeating one of its proper substrings at least twice.",
    constraints: ["The input is non-empty", "The repeated unit must be shorter than the input"],
    functionName: { javascript: "hasRepeatedPattern", python: "has_repeated_pattern" },
    starter: { javascript: "function hasRepeatedPattern(text) {\n  // Return true or false\n}\n", python: "def has_repeated_pattern(text):\n    # Return True or False\n    pass\n" },
    sampleCases: [{ input: ["abab"], expected: true }, { input: ["aba"], expected: false }],
    testCases: [{ input: ["abab"], expected: true }, { input: ["aba"], expected: false }, { input: ["abcabcabc"], expected: true, hidden: true }, { input: ["a"], expected: false, hidden: true }, { input: ["zzzz"], expected: true, hidden: true }],
  },
  {
    id: "STR-15", topic: "strings", title: "One edit away", difficulty: "medium", pattern: "Two pointers",
    statement: "Return true when two strings are at most one insertion, deletion or replacement apart.",
    constraints: ["Zero edits is allowed", "Comparison is case-sensitive"],
    functionName: { javascript: "isOneEditAway", python: "is_one_edit_away" },
    starter: { javascript: "function isOneEditAway(first, second) {\n  // Return true or false\n}\n", python: "def is_one_edit_away(first, second):\n    # Return True or False\n    pass\n" },
    sampleCases: [{ input: ["pale", "ple"], expected: true }, { input: ["pale", "bake"], expected: false }],
    testCases: [{ input: ["pale", "ple"], expected: true }, { input: ["pale", "bake"], expected: false }, { input: ["pale", "pales"], expected: true, hidden: true }, { input: ["same", "same"], expected: true, hidden: true }, { input: ["a", "abc"], expected: false, hidden: true }],
  },
  {
    id: "STR-16", topic: "strings", title: "Longest palindromic substring", difficulty: "hard", pattern: "Expand around centre",
    statement: "Return the longest contiguous palindromic substring. If several have the same length, return the earliest one.",
    constraints: ["Comparison is case-sensitive", "Return an empty string for empty input"],
    functionName: { javascript: "longestPalindrome", python: "longest_palindrome" },
    starter: { javascript: "function longestPalindrome(text) {\n  // Return the longest palindrome\n}\n", python: "def longest_palindrome(text):\n    # Return the longest palindrome\n    pass\n" },
    sampleCases: [{ input: ["babad"], expected: "bab" }, { input: ["cbbd"], expected: "bb" }],
    testCases: [{ input: ["babad"], expected: "bab" }, { input: ["cbbd"], expected: "bb" }, { input: ["a"], expected: "a", hidden: true }, { input: ["forgeeksskeegfor"], expected: "geeksskeeg", hidden: true }, { input: [""], expected: "", hidden: true }],
  },
  {
    id: "STR-17", topic: "strings", title: "Minimum bracket additions", difficulty: "medium", pattern: "Balance counter",
    statement: "Return the minimum number of parentheses that must be added to make a string of round brackets valid.",
    constraints: ["The input contains only ( and )", "You may add brackets at any position"],
    functionName: { javascript: "minimumBracketAdditions", python: "minimum_bracket_additions" },
    starter: { javascript: "function minimumBracketAdditions(text) {\n  // Return the minimum additions\n}\n", python: "def minimum_bracket_additions(text):\n    # Return the minimum additions\n    pass\n" },
    sampleCases: [{ input: ["())"], expected: 1 }, { input: ["((("], expected: 3 }],
    testCases: [{ input: ["())"], expected: 1 }, { input: ["((("], expected: 3 }, { input: ["()"], expected: 0, hidden: true }, { input: ["()))(("], expected: 4, hidden: true }, { input: [""], expected: 0, hidden: true }],
  },
  {
    id: "STR-18", topic: "strings", title: "Decode character runs", difficulty: "medium", pattern: "Parsing",
    statement: "Expand an encoded string where every letter is followed by a positive integer count.",
    constraints: ["Counts may contain multiple digits", "The encoded input is always valid"],
    functionName: { javascript: "decodeRuns", python: "decode_runs" },
    starter: { javascript: "function decodeRuns(encoded) {\n  // Example: a3b2 -> aaabb\n}\n", python: "def decode_runs(encoded):\n    # Example: a3b2 -> aaabb\n    pass\n" },
    sampleCases: [{ input: ["a3b2c1"], expected: "aaabbc" }, { input: ["x10"], expected: "xxxxxxxxxx" }],
    testCases: [{ input: ["a3b2c1"], expected: "aaabbc" }, { input: ["x10"], expected: "xxxxxxxxxx" }, { input: ["A2b3"], expected: "AAbbb", hidden: true }, { input: ["z1"], expected: "z", hidden: true }],
  },
  {
    id: "STR-19", topic: "strings", title: "Compare version numbers", difficulty: "medium", pattern: "Parsing",
    statement: "Compare two dot-separated version strings. Return -1 if the first is smaller, 1 if it is larger, or 0 if they are equal.",
    constraints: ["Missing revision levels count as zero", "Each revision contains digits only"],
    functionName: { javascript: "compareVersions", python: "compare_versions" },
    starter: { javascript: "function compareVersions(first, second) {\n  // Return -1, 0 or 1\n}\n", python: "def compare_versions(first, second):\n    # Return -1, 0 or 1\n    pass\n" },
    sampleCases: [{ input: ["1.01", "1.001"], expected: 0 }, { input: ["1.0", "1.0.1"], expected: -1 }],
    testCases: [{ input: ["1.01", "1.001"], expected: 0 }, { input: ["1.0", "1.0.1"], expected: -1 }, { input: ["2.1", "2.0.9"], expected: 1, hidden: true }, { input: ["1.0.0", "1"], expected: 0, hidden: true }],
  },
  {
    id: "STR-20", topic: "strings", title: "Smallest covering window", difficulty: "hard", pattern: "Sliding window",
    statement: "Return the length of the shortest substring of text containing every character of target with matching frequencies. Return 0 when impossible.",
    constraints: ["Comparison is case-sensitive", "Repeated target characters must be matched"],
    functionName: { javascript: "smallestCoverLength", python: "smallest_cover_length" },
    starter: { javascript: "function smallestCoverLength(text, target) {\n  // Return the minimum window length\n}\n", python: "def smallest_cover_length(text, target):\n    # Return the minimum window length\n    pass\n" },
    sampleCases: [{ input: ["ADOBECODEBANC", "ABC"], expected: 4 }, { input: ["hello", "xyz"], expected: 0 }],
    testCases: [{ input: ["ADOBECODEBANC", "ABC"], expected: 4 }, { input: ["hello", "xyz"], expected: 0 }, { input: ["aa", "aa"], expected: 2, hidden: true }, { input: ["aaflslflsldkalskaaa", "aaa"], expected: 3, hidden: true }, { input: ["abc", ""], expected: 0, hidden: true }],
  },
];

const arrays: DsaPracticeQuestion[] = [
  {
    id: "ARR-01",
    topic: "arrays",
    title: "Second distinct largest",
    difficulty: "easy",
    pattern: "Single pass",
    statement: "Return the second-largest distinct number in the array. Return null when fewer than two distinct values exist.",
    constraints: ["The array may contain negative numbers", "Repeated maximum values count once"],
    functionName: { javascript: "secondDistinctLargest", python: "second_distinct_largest" },
    starter: {
      javascript: "function secondDistinctLargest(numbers) {\n  // Return a number or null\n}\n",
      python: "def second_distinct_largest(numbers):\n    # Return a number or None\n    pass\n",
    },
    sampleCases: [
      { input: [[12, 35, 1, 10, 34, 1]], expected: 34 },
      { input: [[7, 7]], expected: null },
    ],
    testCases: [
      { input: [[12, 35, 1, 10, 34, 1]], expected: 34 },
      { input: [[7, 7]], expected: null },
      { input: [[-2, -9, -4]], expected: -4, hidden: true },
      { input: [[5, 1, 5, 4]], expected: 4, hidden: true },
    ],
  },
  {
    id: "ARR-02",
    topic: "arrays",
    title: "Move zeroes to the end",
    difficulty: "easy",
    pattern: "Two pointers",
    statement: "Return an array with every zero moved to the end while preserving the relative order of non-zero values.",
    constraints: ["Return a new array or the correctly modified input", "Values may be negative"],
    functionName: { javascript: "moveZeroes", python: "move_zeroes" },
    starter: {
      javascript: "function moveZeroes(numbers) {\n  // Return the reordered array\n}\n",
      python: "def move_zeroes(numbers):\n    # Return the reordered list\n    pass\n",
    },
    sampleCases: [
      { input: [[0, 1, 0, 3, 12]], expected: [1, 3, 12, 0, 0] },
      { input: [[0, 0, 1]], expected: [1, 0, 0] },
    ],
    testCases: [
      { input: [[0, 1, 0, 3, 12]], expected: [1, 3, 12, 0, 0] },
      { input: [[0, 0, 1]], expected: [1, 0, 0] },
      { input: [[1, 2, 3]], expected: [1, 2, 3], hidden: true },
      { input: [[0]], expected: [0], hidden: true },
      { input: [[-1, 0, -2, 0]], expected: [-1, -2, 0, 0], hidden: true },
    ],
  },
  {
    id: "ARR-03",
    topic: "arrays",
    title: "Rotate right",
    difficulty: "medium",
    pattern: "Index manipulation",
    statement: "Return the array after rotating its elements k positions to the right.",
    constraints: ["k may be larger than the array length", "Return an empty array when the input is empty"],
    functionName: { javascript: "rotateRight", python: "rotate_right" },
    starter: {
      javascript: "function rotateRight(numbers, k) {\n  // Return the rotated array\n}\n",
      python: "def rotate_right(numbers, k):\n    # Return the rotated list\n    pass\n",
    },
    sampleCases: [
      { input: [[1, 2, 3, 4, 5], 2], expected: [4, 5, 1, 2, 3] },
      { input: [[1, 2], 5], expected: [2, 1] },
    ],
    testCases: [
      { input: [[1, 2, 3, 4, 5], 2], expected: [4, 5, 1, 2, 3] },
      { input: [[1, 2], 5], expected: [2, 1] },
      { input: [[], 3], expected: [], hidden: true },
      { input: [[-1, -2, -3], 3], expected: [-1, -2, -3], hidden: true },
    ],
  },
  {
    id: "ARR-04",
    topic: "arrays",
    title: "Maximum contiguous sum",
    difficulty: "medium",
    pattern: "Kadane's algorithm",
    statement: "Return the largest possible sum of a non-empty contiguous subarray.",
    constraints: ["The input always contains at least one number", "All values may be negative"],
    functionName: { javascript: "maximumSubarraySum", python: "maximum_subarray_sum" },
    starter: {
      javascript: "function maximumSubarraySum(numbers) {\n  // Return the largest contiguous sum\n}\n",
      python: "def maximum_subarray_sum(numbers):\n    # Return the largest contiguous sum\n    pass\n",
    },
    sampleCases: [
      { input: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], expected: 6 },
      { input: [[-5, -2, -8]], expected: -2 },
    ],
    testCases: [
      { input: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], expected: 6 },
      { input: [[-5, -2, -8]], expected: -2 },
      { input: [[1]], expected: 1, hidden: true },
      { input: [[5, 4, -1, 7, 8]], expected: 23, hidden: true },
    ],
  },
  {
    id: "ARR-05",
    topic: "arrays",
    title: "Pair with target sum",
    difficulty: "medium",
    pattern: "Hash map",
    statement: "Return the indices of the first pair whose values add to target. Return an empty array when no pair exists.",
    constraints: ["Return indices in ascending order", "Use each array position at most once"],
    functionName: { javascript: "pairSumIndices", python: "pair_sum_indices" },
    starter: {
      javascript: "function pairSumIndices(numbers, target) {\n  // Return [firstIndex, secondIndex] or []\n}\n",
      python: "def pair_sum_indices(numbers, target):\n    # Return [first_index, second_index] or []\n    pass\n",
    },
    sampleCases: [
      { input: [[2, 7, 11, 15], 9], expected: [0, 1] },
      { input: [[1, 2, 3], 10], expected: [] },
    ],
    testCases: [
      { input: [[2, 7, 11, 15], 9], expected: [0, 1] },
      { input: [[1, 2, 3], 10], expected: [] },
      { input: [[3, 3], 6], expected: [0, 1], hidden: true },
      { input: [[-4, 8, 5, 1], 4], expected: [0, 1], hidden: true },
    ],
  },
  {
    id: "ARR-06",
    topic: "arrays",
    title: "Product except self",
    difficulty: "hard",
    pattern: "Prefix and suffix",
    statement: "Return an array where each position contains the product of every input value except the value at that position.",
    constraints: ["Do not use division", "The output values fit in a standard integer"],
    functionName: { javascript: "productExceptSelf", python: "product_except_self" },
    starter: {
      javascript: "function productExceptSelf(numbers) {\n  // Return the product array without division\n}\n",
      python: "def product_except_self(numbers):\n    # Return the product list without division\n    pass\n",
    },
    sampleCases: [
      { input: [[1, 2, 3, 4]], expected: [24, 12, 8, 6] },
      { input: [[-1, 1, 0, -3, 3]], expected: [0, 0, 9, 0, 0] },
    ],
    testCases: [
      { input: [[1, 2, 3, 4]], expected: [24, 12, 8, 6] },
      { input: [[-1, 1, 0, -3, 3]], expected: [0, 0, 9, 0, 0] },
      { input: [[2, 3]], expected: [3, 2], hidden: true },
      { input: [[0, 0]], expected: [0, 0], hidden: true },
    ],
  },
  {
    id: "ARR-07", topic: "arrays", title: "Remove duplicates from sorted array", difficulty: "easy", pattern: "Two pointers",
    statement: "Return a new array containing each distinct value from the sorted input exactly once.",
    constraints: ["The input is sorted in ascending order", "The input may be empty"],
    functionName: { javascript: "uniqueSorted", python: "unique_sorted" },
    starter: { javascript: "function uniqueSorted(numbers) {\n  // Return the distinct values\n}\n", python: "def unique_sorted(numbers):\n    # Return the distinct values\n    pass\n" },
    sampleCases: [{ input: [[1, 1, 2, 2, 3]], expected: [1, 2, 3] }, { input: [[]], expected: [] }],
    testCases: [{ input: [[1, 1, 2, 2, 3]], expected: [1, 2, 3] }, { input: [[]], expected: [] }, { input: [[-2, -2, -1, 0, 0]], expected: [-2, -1, 0], hidden: true }, { input: [[5]], expected: [5], hidden: true }],
  },
  {
    id: "ARR-08", topic: "arrays", title: "Missing number", difficulty: "easy", pattern: "Arithmetic or XOR",
    statement: "The array contains distinct values selected from 0 through n, with one value missing. Return the missing value.",
    constraints: ["n equals the array length", "Values are distinct"],
    functionName: { javascript: "findMissingNumber", python: "find_missing_number" },
    starter: { javascript: "function findMissingNumber(numbers) {\n  // Return the missing value\n}\n", python: "def find_missing_number(numbers):\n    # Return the missing value\n    pass\n" },
    sampleCases: [{ input: [[3, 0, 1]], expected: 2 }, { input: [[0, 1]], expected: 2 }],
    testCases: [{ input: [[3, 0, 1]], expected: 2 }, { input: [[0, 1]], expected: 2 }, { input: [[9, 6, 4, 2, 3, 5, 7, 0, 1]], expected: 8, hidden: true }, { input: [[]], expected: 0, hidden: true }],
  },
  {
    id: "ARR-09", topic: "arrays", title: "Merge sorted arrays", difficulty: "easy", pattern: "Two pointers",
    statement: "Merge two ascending arrays into one ascending array while preserving duplicate values.",
    constraints: ["Both inputs are already sorted", "Either input may be empty"],
    functionName: { javascript: "mergeSortedArrays", python: "merge_sorted_arrays" },
    starter: { javascript: "function mergeSortedArrays(first, second) {\n  // Return one sorted array\n}\n", python: "def merge_sorted_arrays(first, second):\n    # Return one sorted list\n    pass\n" },
    sampleCases: [{ input: [[1, 3, 5], [2, 4, 6]], expected: [1, 2, 3, 4, 5, 6] }, { input: [[], [1, 2]], expected: [1, 2] }],
    testCases: [{ input: [[1, 3, 5], [2, 4, 6]], expected: [1, 2, 3, 4, 5, 6] }, { input: [[], [1, 2]], expected: [1, 2] }, { input: [[1, 1], [1, 2]], expected: [1, 1, 1, 2], hidden: true }, { input: [[-3, 0], [-2, 4]], expected: [-3, -2, 0, 4], hidden: true }],
  },
  {
    id: "ARR-10", topic: "arrays", title: "Unique intersection", difficulty: "easy", pattern: "Sets",
    statement: "Return the distinct values present in both arrays, sorted in ascending order.",
    constraints: ["Inputs may contain duplicates", "Return an empty array when there is no overlap"],
    functionName: { javascript: "uniqueIntersection", python: "unique_intersection" },
    starter: { javascript: "function uniqueIntersection(first, second) {\n  // Return sorted shared values\n}\n", python: "def unique_intersection(first, second):\n    # Return sorted shared values\n    pass\n" },
    sampleCases: [{ input: [[1, 2, 2, 1], [2, 2]], expected: [2] }, { input: [[4, 9, 5], [9, 4, 9, 8, 4]], expected: [4, 9] }],
    testCases: [{ input: [[1, 2, 2, 1], [2, 2]], expected: [2] }, { input: [[4, 9, 5], [9, 4, 9, 8, 4]], expected: [4, 9] }, { input: [[], [1]], expected: [], hidden: true }, { input: [[-1, 0, -1], [-1]], expected: [-1], hidden: true }],
  },
  {
    id: "ARR-11", topic: "arrays", title: "Array leaders", difficulty: "medium", pattern: "Reverse scan",
    statement: "Return every value that is greater than all values to its right. The final value is always a leader.",
    constraints: ["Keep leaders in their original order", "The array is non-empty"],
    functionName: { javascript: "findLeaders", python: "find_leaders" },
    starter: { javascript: "function findLeaders(numbers) {\n  // Return leaders in original order\n}\n", python: "def find_leaders(numbers):\n    # Return leaders in original order\n    pass\n" },
    sampleCases: [{ input: [[16, 17, 4, 3, 5, 2]], expected: [17, 5, 2] }, { input: [[5, 4, 3]], expected: [5, 4, 3] }],
    testCases: [{ input: [[16, 17, 4, 3, 5, 2]], expected: [17, 5, 2] }, { input: [[5, 4, 3]], expected: [5, 4, 3] }, { input: [[1, 2, 3]], expected: [3], hidden: true }, { input: [[-1]], expected: [-1], hidden: true }],
  },
  {
    id: "ARR-12", topic: "arrays", title: "Equilibrium index", difficulty: "medium", pattern: "Prefix sum",
    statement: "Return the first index where the sum of values on the left equals the sum on the right. Return -1 if none exists.",
    constraints: ["The value at the index is excluded from both sums", "Negative values are allowed"],
    functionName: { javascript: "equilibriumIndex", python: "equilibrium_index" },
    starter: { javascript: "function equilibriumIndex(numbers) {\n  // Return an index or -1\n}\n", python: "def equilibrium_index(numbers):\n    # Return an index or -1\n    pass\n" },
    sampleCases: [{ input: [[1, 3, 5, 2, 2]], expected: 2 }, { input: [[1, 2, 3]], expected: -1 }],
    testCases: [{ input: [[1, 3, 5, 2, 2]], expected: 2 }, { input: [[1, 2, 3]], expected: -1 }, { input: [[2, 0, 0]], expected: 0, hidden: true }, { input: [[-7, 1, 5, 2, -4, 3, 0]], expected: 3, hidden: true }],
  },
  {
    id: "ARR-13", topic: "arrays", title: "Majority element", difficulty: "medium", pattern: "Boyer-Moore voting",
    statement: "Return the value appearing more than half the time, or null when no majority value exists.",
    constraints: ["The array may be empty", "A candidate must be verified before returning it"],
    functionName: { javascript: "majorityElement", python: "majority_element" },
    starter: { javascript: "function majorityElement(numbers) {\n  // Return the majority value or null\n}\n", python: "def majority_element(numbers):\n    # Return the majority value or None\n    pass\n" },
    sampleCases: [{ input: [[3, 2, 3]], expected: 3 }, { input: [[1, 2, 3]], expected: null }],
    testCases: [{ input: [[3, 2, 3]], expected: 3 }, { input: [[1, 2, 3]], expected: null }, { input: [[2, 2, 1, 1, 1, 2, 2]], expected: 2, hidden: true }, { input: [[]], expected: null, hidden: true }],
  },
  {
    id: "ARR-14", topic: "arrays", title: "Best stock profit", difficulty: "medium", pattern: "Running minimum",
    statement: "Return the maximum profit from buying once and selling once later. Return 0 when no profitable trade exists.",
    constraints: ["A sale must occur after the purchase", "Prices are non-negative"],
    functionName: { javascript: "maximumStockProfit", python: "maximum_stock_profit" },
    starter: { javascript: "function maximumStockProfit(prices) {\n  // Return the best profit\n}\n", python: "def maximum_stock_profit(prices):\n    # Return the best profit\n    pass\n" },
    sampleCases: [{ input: [[7, 1, 5, 3, 6, 4]], expected: 5 }, { input: [[7, 6, 4, 3, 1]], expected: 0 }],
    testCases: [{ input: [[7, 1, 5, 3, 6, 4]], expected: 5 }, { input: [[7, 6, 4, 3, 1]], expected: 0 }, { input: [[1, 2]], expected: 1, hidden: true }, { input: [[3]], expected: 0, hidden: true }],
  },
  {
    id: "ARR-15", topic: "arrays", title: "Longest consecutive sequence", difficulty: "medium", pattern: "Hash set",
    statement: "Return the length of the longest run of consecutive integer values, regardless of their input order.",
    constraints: ["Duplicate values do not extend a run", "Aim for linear time"],
    functionName: { javascript: "longestConsecutiveLength", python: "longest_consecutive_length" },
    starter: { javascript: "function longestConsecutiveLength(numbers) {\n  // Return the longest run length\n}\n", python: "def longest_consecutive_length(numbers):\n    # Return the longest run length\n    pass\n" },
    sampleCases: [{ input: [[100, 4, 200, 1, 3, 2]], expected: 4 }, { input: [[]], expected: 0 }],
    testCases: [{ input: [[100, 4, 200, 1, 3, 2]], expected: 4 }, { input: [[]], expected: 0 }, { input: [[0, 3, 7, 2, 5, 8, 4, 6, 0, 1]], expected: 9, hidden: true }, { input: [[5, 5, 5]], expected: 1, hidden: true }],
  },
  {
    id: "ARR-16", topic: "arrays", title: "Triplets summing to zero", difficulty: "hard", pattern: "Sort and two pointers",
    statement: "Return every unique triplet whose values sum to zero. Sort each triplet and sort the result lexicographically.",
    constraints: ["Do not return duplicate triplets", "Return an empty array when no triplet exists"],
    functionName: { javascript: "zeroSumTriplets", python: "zero_sum_triplets" },
    starter: { javascript: "function zeroSumTriplets(numbers) {\n  // Return sorted unique triplets\n}\n", python: "def zero_sum_triplets(numbers):\n    # Return sorted unique triplets\n    pass\n" },
    sampleCases: [{ input: [[-1, 0, 1, 2, -1, -4]], expected: [[-1, -1, 2], [-1, 0, 1]] }, { input: [[1, 2, 3]], expected: [] }],
    testCases: [{ input: [[-1, 0, 1, 2, -1, -4]], expected: [[-1, -1, 2], [-1, 0, 1]] }, { input: [[1, 2, 3]], expected: [] }, { input: [[0, 0, 0, 0]], expected: [[0, 0, 0]], hidden: true }, { input: [[-2, 0, 1, 1, 2]], expected: [[-2, 0, 2], [-2, 1, 1]], hidden: true }],
  },
  {
    id: "ARR-17", topic: "arrays", title: "Spiral matrix traversal", difficulty: "medium", pattern: "Boundary simulation",
    statement: "Return all values of a rectangular matrix in clockwise spiral order, starting at the top-left corner.",
    constraints: ["Rows have equal length", "The matrix may be empty"],
    functionName: { javascript: "spiralOrder", python: "spiral_order" },
    starter: { javascript: "function spiralOrder(matrix) {\n  // Return values in spiral order\n}\n", python: "def spiral_order(matrix):\n    # Return values in spiral order\n    pass\n" },
    sampleCases: [{ input: [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], expected: [1, 2, 3, 6, 9, 8, 7, 4, 5] }, { input: [[[1, 2, 3, 4]]], expected: [1, 2, 3, 4] }],
    testCases: [{ input: [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], expected: [1, 2, 3, 6, 9, 8, 7, 4, 5] }, { input: [[[1, 2, 3, 4]]], expected: [1, 2, 3, 4] }, { input: [[]], expected: [], hidden: true }, { input: [[[1, 2], [3, 4], [5, 6]]], expected: [1, 2, 4, 6, 5, 3], hidden: true }],
  },
  {
    id: "ARR-18", topic: "arrays", title: "Merge overlapping intervals", difficulty: "medium", pattern: "Sorting",
    statement: "Merge every overlapping interval and return the result ordered by starting value.",
    constraints: ["Each interval is [start, end] with start not greater than end", "Touching intervals overlap"],
    functionName: { javascript: "mergeIntervals", python: "merge_intervals" },
    starter: { javascript: "function mergeIntervals(intervals) {\n  // Return merged intervals\n}\n", python: "def merge_intervals(intervals):\n    # Return merged intervals\n    pass\n" },
    sampleCases: [{ input: [[[1, 3], [2, 6], [8, 10], [15, 18]]], expected: [[1, 6], [8, 10], [15, 18]] }, { input: [[[1, 4], [4, 5]]], expected: [[1, 5]] }],
    testCases: [{ input: [[[1, 3], [2, 6], [8, 10], [15, 18]]], expected: [[1, 6], [8, 10], [15, 18]] }, { input: [[[1, 4], [4, 5]]], expected: [[1, 5]] }, { input: [[]], expected: [], hidden: true }, { input: [[[5, 7], [1, 2], [2, 4]]], expected: [[1, 4], [5, 7]], hidden: true }],
  },
  {
    id: "ARR-19", topic: "arrays", title: "Trapped rain water", difficulty: "hard", pattern: "Two pointers",
    statement: "Given bar heights of width one, return the total units of water trapped after rainfall.",
    constraints: ["Heights are non-negative", "Fewer than three bars trap no water"],
    functionName: { javascript: "trappedWater", python: "trapped_water" },
    starter: { javascript: "function trappedWater(heights) {\n  // Return trapped water units\n}\n", python: "def trapped_water(heights):\n    # Return trapped water units\n    pass\n" },
    sampleCases: [{ input: [[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], expected: 6 }, { input: [[4, 2, 0, 3, 2, 5]], expected: 9 }],
    testCases: [{ input: [[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], expected: 6 }, { input: [[4, 2, 0, 3, 2, 5]], expected: 9 }, { input: [[1, 2]], expected: 0, hidden: true }, { input: [[3, 0, 3]], expected: 3, hidden: true }],
  },
  {
    id: "ARR-20", topic: "arrays", title: "Smallest missing positive", difficulty: "hard", pattern: "Index placement",
    statement: "Return the smallest positive integer that does not appear in the unsorted array.",
    constraints: ["The desired solution uses constant extra space", "Zero and negative values do not count as positive"],
    functionName: { javascript: "smallestMissingPositive", python: "smallest_missing_positive" },
    starter: { javascript: "function smallestMissingPositive(numbers) {\n  // Return the missing positive integer\n}\n", python: "def smallest_missing_positive(numbers):\n    # Return the missing positive integer\n    pass\n" },
    sampleCases: [{ input: [[1, 2, 0]], expected: 3 }, { input: [[3, 4, -1, 1]], expected: 2 }],
    testCases: [{ input: [[1, 2, 0]], expected: 3 }, { input: [[3, 4, -1, 1]], expected: 2 }, { input: [[7, 8, 9, 11, 12]], expected: 1, hidden: true }, { input: [[1, 1]], expected: 2, hidden: true }, { input: [[]], expected: 1, hidden: true }],
  },
];

export const dsaQuestions: Record<PracticeTopic, DsaPracticeQuestion[]> = { strings, arrays };

export function getDsaQuestions(topic: PracticeTopic): DsaPracticeQuestion[] {
  return dsaQuestions[topic];
}
