import type { QuestionDef } from "./types";

export const easyQuestions: QuestionDef[] = [
  // ───────────── Company ─────────────
  {
    id: "E001",
    datasetId: "company",
    title: "High earners",
    description:
      "List the first name, last name and salary of every employee whose salary is greater than ₹80,000. Sort by salary, highest first.",
    difficulty: "easy",
    tags: ["SELECT", "WHERE", "ORDER BY"],
    solution:
      "SELECT first_name, last_name, salary FROM employees WHERE salary > 80000 ORDER BY salary DESC",
    orderMatters: true,
    hints: ["Filter with WHERE salary > 80000 and sort with ORDER BY salary DESC."],
  },
  {
    id: "E002",
    datasetId: "company",
    title: "Department directory",
    description:
      "Show the name and location of every department, sorted alphabetically by department name.",
    difficulty: "easy",
    tags: ["SELECT", "ORDER BY"],
    solution: "SELECT department_name, location FROM departments ORDER BY department_name",
    orderMatters: true,
    hints: ["Select two columns from departments and add ORDER BY department_name."],
  },
  {
    id: "E003",
    datasetId: "company",
    title: "Headcount",
    description: "How many employees does the company have? Return a single column named total_employees.",
    difficulty: "easy",
    tags: ["AGGREGATION"],
    solution: "SELECT COUNT(*) AS total_employees FROM employees",
    orderMatters: false,
    hints: ["COUNT(*) counts every row. Alias it with AS total_employees."],
  },
  {
    id: "E004",
    datasetId: "company",
    title: "Engineering team",
    description:
      "List the first and last names of all employees in department 1 (Engineering), sorted by last name.",
    difficulty: "easy",
    tags: ["SELECT", "WHERE", "ORDER BY"],
    solution:
      "SELECT first_name, last_name FROM employees WHERE department_id = 1 ORDER BY last_name",
    orderMatters: true,
    hints: ["Filter on department_id = 1."],
  },
  {
    id: "E005",
    datasetId: "company",
    title: "Salary range",
    description:
      "Find the highest and lowest salary in the company. Return two columns: max_salary and min_salary.",
    difficulty: "easy",
    tags: ["AGGREGATION"],
    solution: "SELECT MAX(salary) AS max_salary, MIN(salary) AS min_salary FROM employees",
    orderMatters: false,
    hints: ["Use MAX() and MIN() in the same SELECT."],
  },
  {
    id: "E006",
    datasetId: "company",
    title: "Average salary",
    description:
      "What is the average salary across all employees, rounded to the nearest whole number? Return it as avg_salary.",
    difficulty: "easy",
    tags: ["AGGREGATION"],
    solution: "SELECT ROUND(AVG(salary)) AS avg_salary FROM employees",
    orderMatters: false,
    hints: ["Wrap AVG(salary) in ROUND()."],
  },
  {
    id: "E007",
    datasetId: "company",
    title: "Class of 2023",
    description:
      "List the first name and hire date of every employee hired during 2023, earliest hire first.",
    difficulty: "easy",
    tags: ["WHERE", "BETWEEN", "ORDER BY"],
    solution:
      "SELECT first_name, hire_date FROM employees WHERE hire_date BETWEEN '2023-01-01' AND '2023-12-31' ORDER BY hire_date",
    orderMatters: true,
    hints: ["Dates are stored as YYYY-MM-DD text, so BETWEEN '2023-01-01' AND '2023-12-31' works."],
  },
  {
    id: "E008",
    datasetId: "company",
    title: "Names starting with A",
    description:
      "Find every employee whose first name starts with the letter A. Return first_name and last_name sorted by first name.",
    difficulty: "easy",
    tags: ["LIKE", "ORDER BY"],
    solution:
      "SELECT first_name, last_name FROM employees WHERE first_name LIKE 'A%' ORDER BY first_name",
    orderMatters: true,
    hints: ["LIKE 'A%' matches strings that begin with A."],
  },
  {
    id: "E009",
    datasetId: "company",
    title: "Unassigned employees",
    description:
      "Which employees are not assigned to any department? Return first_name and last_name.",
    difficulty: "easy",
    tags: ["WHERE", "NULL"],
    solution: "SELECT first_name, last_name FROM employees WHERE department_id IS NULL",
    orderMatters: false,
    hints: ["Compare with IS NULL, not = NULL."],
  },
  {
    id: "E010",
    datasetId: "company",
    title: "Office cities",
    description: "List each distinct location where the company has a department, alphabetically.",
    difficulty: "easy",
    tags: ["DISTINCT", "ORDER BY"],
    solution: "SELECT DISTINCT location FROM departments ORDER BY location",
    orderMatters: true,
    hints: ["DISTINCT removes duplicate values."],
  },
  {
    id: "E011",
    datasetId: "company",
    title: "Top three salaries",
    description: "Show the first name and salary of the three highest-paid employees, highest first.",
    difficulty: "easy",
    tags: ["ORDER BY", "LIMIT"],
    solution: "SELECT first_name, salary FROM employees ORDER BY salary DESC LIMIT 3",
    orderMatters: true,
    hints: ["ORDER BY salary DESC then LIMIT 3."],
  },
  {
    id: "E012",
    datasetId: "company",
    title: "Big budgets",
    description:
      "List the name and budget of every project with a budget of at least ₹10,00,000, largest budget first.",
    difficulty: "easy",
    tags: ["WHERE", "ORDER BY"],
    solution:
      "SELECT project_name, budget FROM projects WHERE budget >= 1000000 ORDER BY budget DESC",
    orderMatters: true,
    hints: ["Ten lakh is 1000000."],
  },
  {
    id: "E013",
    datasetId: "company",
    title: "Ongoing projects",
    description:
      "Which projects have not finished yet (no end date)? Return project_name sorted alphabetically.",
    difficulty: "easy",
    tags: ["WHERE", "NULL", "ORDER BY"],
    solution: "SELECT project_name FROM projects WHERE end_date IS NULL ORDER BY project_name",
    orderMatters: true,
    hints: ["An unfinished project has end_date IS NULL."],
  },
  {
    id: "E014",
    datasetId: "company",
    title: "Hours on Atlas",
    description:
      "How many hours in total were logged on project 1 (Atlas Platform)? Return the value as total_hours.",
    difficulty: "easy",
    tags: ["AGGREGATION", "WHERE"],
    solution: "SELECT SUM(hours_worked) AS total_hours FROM employee_projects WHERE project_id = 1",
    orderMatters: false,
    hints: ["SUM(hours_worked) with a WHERE on project_id."],
  },
  {
    id: "E015",
    datasetId: "company",
    title: "Mid-range salaries",
    description:
      "List first name and salary for employees earning between ₹50,000 and ₹70,000 inclusive, lowest salary first.",
    difficulty: "easy",
    tags: ["BETWEEN", "ORDER BY"],
    solution:
      "SELECT first_name, salary FROM employees WHERE salary BETWEEN 50000 AND 70000 ORDER BY salary",
    orderMatters: true,
    hints: ["BETWEEN is inclusive on both ends."],
  },
  {
    id: "E016",
    datasetId: "company",
    title: "Company email list",
    description:
      "Return the email address of every employee whose email ends with '@company.com', sorted alphabetically. Name the column email.",
    difficulty: "easy",
    tags: ["LIKE", "ORDER BY"],
    solution: "SELECT email FROM employees WHERE email LIKE '%@company.com' ORDER BY email",
    orderMatters: true,
    hints: ["Use LIKE '%@company.com'."],
  },

  // ───────────── E-Commerce ─────────────
  {
    id: "E017",
    datasetId: "ecommerce",
    title: "Electronics catalogue",
    description:
      "List the product name and price of every product in the Electronics category, most expensive first.",
    difficulty: "easy",
    tags: ["WHERE", "ORDER BY"],
    solution:
      "SELECT product_name, price FROM products WHERE category = 'Electronics' ORDER BY price DESC",
    orderMatters: true,
    hints: ["String comparisons need quotes: category = 'Electronics'."],
  },
  {
    id: "E018",
    datasetId: "ecommerce",
    title: "Out of stock",
    description: "Which products are out of stock? Return product_name in alphabetical order.",
    difficulty: "easy",
    tags: ["WHERE", "ORDER BY"],
    solution: "SELECT product_name FROM products WHERE stock = 0 ORDER BY product_name",
    orderMatters: true,
    hints: ["Out of stock means stock = 0."],
  },
  {
    id: "E019",
    datasetId: "ecommerce",
    title: "Metro customers",
    description:
      "List the names of customers who live in Mumbai or Delhi, sorted alphabetically. Name the column name.",
    difficulty: "easy",
    tags: ["IN", "ORDER BY"],
    solution: "SELECT name FROM customers WHERE city IN ('Mumbai', 'Delhi') ORDER BY name",
    orderMatters: true,
    hints: ["city IN ('Mumbai', 'Delhi') is neater than two OR conditions."],
  },
  {
    id: "E020",
    datasetId: "ecommerce",
    title: "Cancelled orders",
    description:
      "Show the order_id and order_date of every cancelled order, oldest first.",
    difficulty: "easy",
    tags: ["WHERE", "ORDER BY"],
    solution:
      "SELECT order_id, order_date FROM orders WHERE status = 'cancelled' ORDER BY order_date",
    orderMatters: true,
    hints: ["Status values are lowercase: 'cancelled'."],
  },
  {
    id: "E021",
    datasetId: "ecommerce",
    title: "Order volume",
    description: "How many orders have been placed in total? Return the count as total_orders.",
    difficulty: "easy",
    tags: ["AGGREGATION"],
    solution: "SELECT COUNT(*) AS total_orders FROM orders",
    orderMatters: false,
    hints: ["COUNT(*) on the orders table."],
  },
  {
    id: "E022",
    datasetId: "ecommerce",
    title: "Delivered revenue",
    description:
      "What is the total amount of all delivered orders? Return it as total_revenue.",
    difficulty: "easy",
    tags: ["AGGREGATION", "WHERE"],
    solution:
      "SELECT SUM(total_amount) AS total_revenue FROM orders WHERE status = 'delivered'",
    orderMatters: false,
    hints: ["SUM(total_amount) filtered to status = 'delivered'."],
  },
  {
    id: "E023",
    datasetId: "ecommerce",
    title: "Largest order",
    description: "Find the order with the highest total amount. Return order_id and total_amount.",
    difficulty: "easy",
    tags: ["ORDER BY", "LIMIT"],
    solution: "SELECT order_id, total_amount FROM orders ORDER BY total_amount DESC LIMIT 1",
    orderMatters: false,
    hints: ["Sort descending and take one row."],
  },
  {
    id: "E024",
    datasetId: "ecommerce",
    title: "Budget picks",
    description: "List the five cheapest products: product_name and price, cheapest first.",
    difficulty: "easy",
    tags: ["ORDER BY", "LIMIT"],
    solution: "SELECT product_name, price FROM products ORDER BY price ASC LIMIT 5",
    orderMatters: true,
    hints: ["ORDER BY price ASC LIMIT 5."],
  },
  {
    id: "E025",
    datasetId: "ecommerce",
    title: "New customers",
    description:
      "Which customers signed up on or after 1 January 2024? Return name and signup_date, earliest first.",
    difficulty: "easy",
    tags: ["WHERE", "ORDER BY"],
    solution:
      "SELECT name, signup_date FROM customers WHERE signup_date >= '2024-01-01' ORDER BY signup_date",
    orderMatters: true,
    hints: ["Compare the date text directly: signup_date >= '2024-01-01'."],
  },
  {
    id: "E026",
    datasetId: "ecommerce",
    title: "Product categories",
    description: "List each distinct product category alphabetically. Name the column category.",
    difficulty: "easy",
    tags: ["DISTINCT", "ORDER BY"],
    solution: "SELECT DISTINCT category FROM products ORDER BY category",
    orderMatters: true,
    hints: ["SELECT DISTINCT category."],
  },
  {
    id: "E027",
    datasetId: "ecommerce",
    title: "Bulk line items",
    description:
      "Find every order item where the quantity is 2 or more. Return order_id, product_id and quantity, sorted by order_id then product_id.",
    difficulty: "easy",
    tags: ["WHERE", "ORDER BY"],
    solution:
      "SELECT order_id, product_id, quantity FROM order_items WHERE quantity >= 2 ORDER BY order_id, product_id",
    orderMatters: true,
    hints: ["Two sort keys: ORDER BY order_id, product_id."],
  },
  {
    id: "E028",
    datasetId: "ecommerce",
    title: "Average product price",
    description:
      "What is the average product price, rounded to 2 decimal places? Return it as avg_price.",
    difficulty: "easy",
    tags: ["AGGREGATION"],
    solution: "SELECT ROUND(AVG(price), 2) AS avg_price FROM products",
    orderMatters: false,
    hints: ["ROUND(AVG(price), 2)."],
  },

  // ───────────── University ─────────────
  {
    id: "E029",
    datasetId: "university",
    title: "Honour roll",
    description:
      "List the student_name and cgpa of every student with a CGPA of 8.5 or higher, highest CGPA first.",
    difficulty: "easy",
    tags: ["WHERE", "ORDER BY"],
    solution:
      "SELECT student_name, cgpa FROM students WHERE cgpa >= 8.5 ORDER BY cgpa DESC",
    orderMatters: true,
    hints: ["Filter with cgpa >= 8.5."],
  },
  {
    id: "E030",
    datasetId: "university",
    title: "Computer Science students",
    description:
      "List the names of all students in the Computer Science department, alphabetically. Name the column student_name.",
    difficulty: "easy",
    tags: ["WHERE", "ORDER BY"],
    solution:
      "SELECT student_name FROM students WHERE department = 'Computer Science' ORDER BY student_name",
    orderMatters: true,
    hints: ["department = 'Computer Science'."],
  },
  {
    id: "E031",
    datasetId: "university",
    title: "Four-credit courses",
    description: "Which courses are worth 4 credits? Return course_name alphabetically.",
    difficulty: "easy",
    tags: ["WHERE", "ORDER BY"],
    solution: "SELECT course_name FROM courses WHERE credits = 4 ORDER BY course_name",
    orderMatters: true,
    hints: ["Filter on credits = 4."],
  },
  {
    id: "E032",
    datasetId: "university",
    title: "No CGPA yet",
    description:
      "Which students do not have a CGPA recorded? Return student_name alphabetically.",
    difficulty: "easy",
    tags: ["NULL", "ORDER BY"],
    solution: "SELECT student_name FROM students WHERE cgpa IS NULL ORDER BY student_name",
    orderMatters: true,
    hints: ["cgpa IS NULL."],
  },
  {
    id: "E033",
    datasetId: "university",
    title: "Average CGPA",
    description:
      "What is the average CGPA of students who have one, rounded to 2 decimals? Return it as avg_cgpa.",
    difficulty: "easy",
    tags: ["AGGREGATION"],
    solution: "SELECT ROUND(AVG(cgpa), 2) AS avg_cgpa FROM students",
    orderMatters: false,
    hints: ["AVG ignores NULL values automatically."],
  },
  {
    id: "E034",
    datasetId: "university",
    title: "Counting A grades",
    description: "How many enrollments received an A grade? Return the count as a_grades.",
    difficulty: "easy",
    tags: ["AGGREGATION", "WHERE"],
    solution: "SELECT COUNT(*) AS a_grades FROM enrollments WHERE grade = 'A'",
    orderMatters: false,
    hints: ["COUNT(*) with WHERE grade = 'A'."],
  },
  {
    id: "E035",
    datasetId: "university",
    title: "Mathematics faculty",
    description:
      "List the names of professors in the Mathematics department, alphabetically. Name the column name.",
    difficulty: "easy",
    tags: ["WHERE", "ORDER BY"],
    solution: "SELECT name FROM professors WHERE department = 'Mathematics' ORDER BY name",
    orderMatters: true,
    hints: ["Filter professors by department."],
  },
  {
    id: "E036",
    datasetId: "university",
    title: "Final-year students",
    description:
      "List student_name and semester for students in semester 7, sorted by name.",
    difficulty: "easy",
    tags: ["WHERE", "ORDER BY"],
    solution:
      "SELECT student_name, semester FROM students WHERE semester = 7 ORDER BY student_name",
    orderMatters: true,
    hints: ["semester = 7."],
  },
];
